//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.27 at 01:48:33 PM EEST 
//


package com.homework.xml.iban;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IbanList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IbanList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="iban">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="iban" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IbanList", propOrder = {
    "iban"
})
public class IbanList {

    protected List<IbanList.Iban> iban;

    /**
     * Gets the value of the iban property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iban property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIban().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IbanList.Iban }
     * 
     * 
     */
    public List<IbanList.Iban> getIban() {
        if (iban == null) {
            iban = new ArrayList<IbanList.Iban>();
        }
        return this.iban;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="iban" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "iban",
        "valid"
    })
    public static class Iban {

        @XmlElement(required = true)
        protected String iban;
        protected boolean valid;

        /**
         * Gets the value of the iban property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIban() {
            return iban;
        }

        /**
         * Sets the value of the iban property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIban(String value) {
            this.iban = value;
        }

        /**
         * Gets the value of the valid property.
         * 
         */
        public boolean isValid() {
            return valid;
        }

        /**
         * Sets the value of the valid property.
         * 
         */
        public void setValid(boolean value) {
            this.valid = value;
        }

    }

}
